services:
  juice:
    image: bkimminich/juice-shop:latest
    container_name: juice
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - scan-net

  zap-runner:
    image: zaproxy/zap-stable:latest
    container_name: zap-runner
    working_dir: /zap
    volumes:
      - ./wrk:/zap/wrk
    networks:
      - scan-net

  nuclei:
    image: projectdiscovery/nuclei:latest
    container_name: nuclei
    volumes:
      - ./reports:/reports
    networks:
      - scan-net

  nikto:
    image: alpine/nikto:latest
    container_name: nikto
    volumes:
      - ./reports:/reports
    networks:
      - scan-net

networks:
  scan-net:
    driver: bridge
