services:
  juice:
    image: bkimminich/juice-shop:latest
    container_name: juice
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - juice_data:/data

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    restart: unless-stopped
    ports:
      - "8025:8025"

  zap:
    image: zaproxy/zap-stable
    container_name: zap
    tty: true
    stdin_open: true
    command:
      [
        "zap.sh",
        "-daemon",
        "-host",
        "0.0.0.0",
        "-port",
        "8090",
        "-config",
        "api.disablekey=true",
      ]
    ports:
      - "8090:8090"
    volumes:
      - ./zap-wrk:/zap/wrk
    depends_on:
      - juice

volumes:
  juice_data:
