services:
  juice:
    image: bkimminich/juice-shop:latest
    container_name: juice
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - juice_data:/data

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    restart: unless-stopped
    ports:
      - "8025:8025"

volumes:
  juice_data:
